# -*-tcl-*-
::msgcat::mcmset de {
    "&File"                 "&Datei"
    "&Preferences"          "&Einstellungen"
    "&Emoticons"            "E&moticons"
    "&Visibility"           "&Ansicht"
    "&Alerts"               "A&larme"
    "&Debug"                "&Fehlersuche"
    "&Help"                 "&Hilfe"

    "&Login"                "A&nmelden"
    "&Logout"               "A&bmelden"
    "Login via &IRC..."     "Anmelden \u00fcber &IRC..."
    "&Save options"         "Optionen &speichern"
    "Open &whiteboard"      "&Whiteboard \u00f6ffnen"
    "Open &paste dialog"    "&Paste Dialog \u00f6ffnen"
    "&Install application"  "Anwendung &installieren"
    "E&xit"                 "B&eenden"

    "&Display online users" "&Aktive Benutzer anzeigen"
    "&Enable whiteboard"    "&Whiteboard aktivieren"
    "Auto &bookmark"        "A&utomatische Lesezeichen"
    "Auto-i&nit Babelfish"  "Auto-i&nit Babelfish"

    "&Colors..."            "&Farben..."
    "&Font..."              "&Schriftart..."
    "&User details..."      "&Einzelheiten des Benutzers..."
    "&Input method..."      "E&ingabemethode..."
    "&Options..."           "&Optionen..."
    "&Tk themes"            "&Tk Motive"

    "&Local chat logging"   "&Unterhaltungen lokal mitschreiben"
    "&Disabled"             "&Gesperrt"
    "&To file..."           "&In Datei..."
    "&Load file..."         "&Datei laden..."

    "&Server chat logging"  "Unte&rhaltung auf dem Server mitschreiben"
    "L&og my messages, do not log my actions (old style)" \
        "&Mitschreiben meiner Nachrichten, aber nicht meiner Aktionen (alter Stil)"
    "&Log my messages and actions" "M&itschreiben meiner Nachrichten und Aktionen"
    "Do &not log my messages and actions" \
	"&Weder meine Nachrichten noch meine Aktionen mitschreiben"

    "Loading server &history"    "&Lade alte Eintr\u00e4ge vom Server"
    "Do &NOT load any history"   "&KEINE alten Eintr\u00e4ge laden"
    "&Ask me which logs to load" "&Frage welche alten Eintr\u00e4ge zu laden sind"
    "Load at least %d lines"     "Mindestens %d Zeilen laden"

    "&One to One chats"     "&Vier-Augen Unterhaltungen"
    "&Keep all chat in one window" "Alle Unterhaltungen in einem Fenster &behalten"
    "&Popup a new window"   "Erstelle neues &Fenster"
    "Open in new &tab"      "Ein neues &Unterfenster \u00f6ffnen"

    "&Auto away"            "Auto&matisch Abwesend"
    "After %d minutes"      "Nach %d Minuten"

    "&Show emoticons..."    "Emoticons &anzeigen..."
    "&Use emoticons"        "Emoticons &benutzen"
    "&Animate emoticons"    "A&nimierte Emoticons"
    "U&pdate emoticons"     "Emoticons &erneuern"
    "&Insert"               "E&inf\u00fcgen"

    "Hide &single dot messages"         "&Punktnachrichten verstecken"
    "Hide &online/away status messages" "&An-/Abwesend Status verstecken"
    "Hide &logon/logoff messages"       "A&n-/Abmeldungen verstecken"
    "Hide &all system messages"         "A&lle Systemmeldungen verstecken"
    "Hide &error messages"  "&Fehlermeldungen verstecken"
    "Hide &timestamps"      "&Zeitstempel verstecken"
    "Hide status&bar"       "&Statuszeile verstecken"
    "Hide all &users"       "All&e Benutzer verstecken"
    "Sho&w all users"       "Alle Ben&utzer zeigen"
    "&Hide users"           "&Benutzer verstecken"
    "Show &statusbar history" "Al&te Statuszeileneintr\u00e4ge anzeigen"
    "Show &current history in new pane" \
	"&Derzeitige alten Eintr\u00e4ge in neuem Unterfenster anzeigen"

    "Alert when any &message received" \
	"&Alarm bei jeder empfangenen Nachricht"
    "Alert when &username mentioned" \
	"A&larm bei Erw\u00e4hnung des Benutzernamens"
    "Alert when s&omeone speaks who was quiet" \
	"Ala&rm wenn jemand spricht, der vorher schwieg"
    "Alert when &specified subject mentioned" \
	"Alar&m bei Erw\u00e4hnung eines bestimmten Themas"
    "&Beep on alert"                           "&Bei einem Alarm piepen"
    "&Raise to top on alert"                   "B&ei einem Alarm anzeigen"
    "Alert on regular &posts"                  "Alarm bei &normalen Nachrichten"
    "Alert on &whispers and \"/me\" posts"     "Alarm bei &whispers und \"/me\" Nachrichten"

    "&Reload script"        "Sk&ript erneut laden"
    "Re&start script"       "S&kript erneut starten"
    "E&valuate selection"   "&Selektion evaluieren"
    "&Allow remote control" "&Fernsteuerung erlauben"
    "&Get user versions"    "&Versionen der Benutzer holen"
    "Reload &history"       "Alte &Eintr\u00e4ge erneut laden"
    "&Error logging"        "&Fehler Erfassung"
    "&Log level"            "&Log Priorit\u00e4t"
    "To &stderr"            "Nach &stderr"
    "To &file..."           "In &Datei..."
    "Console"               "Konsole"

    "&Quick Help..."        "&Kurzanleitung..."
    "Help (&wiki)..."       "Hilfe (&wiki)..."
    "&Check version"        "&Version \u00fcberpr\u00fcfen"
    "&View ChangeLog..."    "&ChangeLog anzeigen..."
    "&About..."             "&\u00dcber..."

    "Hide user"             "Benutzer verstecken"
    "Set/Unset bookmark"    "Lesezeichen (zur\u00fcck)setzen"
    "Prev bookmark"         "Vorangegangenes Lesezeichen"
    "Next bookmark"         "N\u00e4chstes Lesezeichen"
    "Clear bookmarks"       "Lesezeichen l\u00f6schen"
    "Google selection"      "Google selection"

    "Initialize translation" "\u00dcbersetzung einleiten"
    "Translate selection"    "Selektion \u00fcbersetzen"

    OK      "OK"
    Cancel  "Abbruch"
    Yes     "Ja"
    No      "Nein"
    Close   "Schlie\u00dfen"
    Send    "Absenden"
    Reply   "Reply"
    Ready   "Fertig"
    Clear   "L\u00f6schen"
    Quit    "Beenden"
    Login   "Anmelden"
    Post    "Senden"
    Error   "Fehler"

    "All users"             "Alle Benutzer"
    "Disconnected from jabber server." \
	"Verbindung zum Jabber Server wurde getrennt."
    "Connected to %s, sending credentials." "Zu %s verbunden, sende Anmeldedaten."

    "Load History From Logs" "Alte Log-Eintr\u00e4ge laden"
    "Please select how far back you want to load:" \
        "Wie weit zur\u00fcck sollen die Eintr\u00e4gen geladen werden:"

    "Subject" "Betreff"
    "%s - tkchat message" "%s - Tkchat Nachricht"
    "Re: %s" "Wg: %s"

    "Subscribe request from %s" "Subskriptionsanfrage von %s"
    "Do you want to let %s add you to their roster?" \
        "Darf %s Sie in ihre/seine Liste eintragen?"

    "Tkchat confirm quit"            "Tkchat-Beenden best\u00e4tigen."
    "Are you sure you want to quit?" "Wollen Sie wirklich beenden?"
}

# Logon dialog
::msgcat::mcset de {
    "Use pro&xy"                  "Pro&xy-Server verwenden"
    "&Proxy host:port"            "&Proxy host:port"
    "Proxy auth &username"        "Proxy-Ben&utzername"
    "Proxy auth pa&ssword"        "Proxy-Pa&sswort"
    "J&ID | Nick"                 "J&ID | Nick"
    "Chat p&assword"              "Chat-P&asswort"
    "&Remember chat password"     "Chat-Passwort &merken"
    "&Jabber server:port"         "&Jabber Server:Port"
    "Jab&ber resource"            "Ja&bber-Ressource"
    "Jabber con&ference"          "Jabber-Kon&ferenz"
    "N&o SSL"                     "&Kein SSL"
    "Jabber SSL"                  "Jabbe&r SSL"
    "STARTTLS"                    "STARTTLS"
    "Auto-&connect"               "Auto-An&melden"
    "&Validate SSL certificates"  "SSL-Zertifikate pr\u00fcfen"
    "&Quit"                       "B&eenden"
}
