# -*-tcl-*-
::msgcat::mcmset en {
    "&File"                 "&File"
    "&Preferences"          "&Preferences"
    "&Emoticons"            "&Emoticons"
    "&Visibility"           "&Visibility"
    "&Alerts"               "&Alerts"
    "&Debug"                "&Debug"
    "&Help"                 "&Help"

    "&Login"                "&Connect"
    "&Logout"               "&Disconnect"
    "Login via &IRC..."     "Login via &IRC..."
    "&Save options"         "&Save options"
    "Open &whiteboard"      "Open &whiteboard"
    "Open &paste dialog"    "Open &paste dialog"
    "&Install application"  "&Install application"
    "E&xit"                 "E&xit"

    "&Display online users" "&Display online users"
    "&Enable whiteboard"    "&Enable whiteboard"
    "Auto &bookmark"        "Auto &bookmark"
    "Auto-i&nit Babelfish"  "Auto-i&nit Babelfish"

    "&Colors..."            "&Colors..."
    "&Font..."              "&Font..."
    "&User details..."      "&User details..."
    "&Input method..."      "&Input method..."
    "&Options..."           "&Options..."
    "&Tk themes"            "&Tk themes"

    "&Local chat logging"   "&Local chat logging"
    "&Disabled"             "&Disabled"
    "&To file..."           "&To file..."
    "&Load file..."         "&Load file..."

    "&Server chat logging" "&Server chat logging"
    "L&og my messages, do not log my actions (old style)" \
        "L&og my messages, do not log my actions (old style)"
    "&Log my messages and actions" "&Log my messages and actions"
    "Do &not log my messages and actions" "Do &not log my messages and actions"

    "Loading server &history" "Loading server &history"
    "Do &NOT load any history" "Do &NOT load any history"
    "&Ask me which logs to load" "&Ask me which logs to load"
    "Load at least %d lines" "Load at least %d lines"

    "&One to One chats"     "&One to One chats"
    "&Keep all chat in one window" "&Keep all chat in one window"
    "&Popup a new window"   "&Popup a new window"
    "Open in new &tab"      "Open in new &tab"

    "&Auto away"            "&Auto away"
    "&Disabled"             "&Disabled"
    "After %d minutes"      "After %d minutes"

    "&Show emoticons..."    "&Show emoticons..."
    "&Use emoticons"        "&Use emoticons"
    "&Animate emoticons"    "&Animate emoticons"
    "U&pdate emoticons"     "U&pdate emoticons"
    "&Insert"               "&Insert"

    "Hide &single dot messages" "Hide &single dot messages"
    "Hide &online/away status messages" "Hide &online/away status messages"
    "Hide &logon/logoff messages" "Hide &logon/logoff messages"
    "Hide &all system messages" "Hide &all system messages"
    "Hide &error messages"  "Hide &error messages"
    "Hide &timestamps"      "Hide &timestamps"
    "Hide status&bar"       "Hide status&bar"
    "Hide all &users"       "Hide all &users"
    "Sho&w all users"       "Sho&w all users"
    "&Hide users"           "&Hide users"
    "Show &statusbar history" "Show &statusbar history"
    "Show &current history in new pane" "Show &current history in new pane"

    "Alert when any &message received" "Alert when any &message received"
    "Alert when &username mentioned" "Alert when &username mentioned"
    "Alert when s&omeone speaks who was quiet" \
        "Alert when s&omeone speaks who was quiet"
    "Alert when &specified subject mentioned" \
        "Alert when &specified subject mentioned"
    "&Beep on alert"         "&Beep on alert"
    "&Raise to top on alert" "&Raise to top on alert"
    "Alert on regular &posts" "Alert on regular &posts"
    "Alert on &whispers and \"/me\" posts" "Alert on &whispers and \"/me\" posts"

    "&Reload script"        "&Reload script"
    "Re&start script"       "Re&start script"
    "E&valuate selection"   "E&valuate selection"
    "&Allow remote control" "&Allow remote control"
    "&Get user versions"    "&Get user versions"
    "Reload &history"       "Reload &history"
    "&Error logging"        "&Error logging"
    "&Log level"            "&Log level"
    "To &stderr"            "To &stderr"
    "To &file..."           "To &file..."

    "&Quick help..."        "&Quick help..."
    "Help (&wiki)..."       "Help (&wiki)..."
    "&Check version"        "&Check version"
    "&View Change&Log..."   "&View ChangeLog..."
    "&About..."             "&About..."

    "Hide user"             "Hide user"
    "Set/Unset bookmark"    "Set/Unset bookmark"
    "Prev bookmark"         "Prev bookmark"
    "Next bookmark"         "Next bookmark"
    "Clear bookmarks"       "Clear bookmarks"
    "Google selection"      "Google selection"

    "Initialize translation" "Initialize translation"
    "Translate selection"    "Translate selection"

    OK     "OK"
    Cancel "Cancel"
    Close  "Close"
    Reply  "Reply"
    Ready  "Ready"

    "All users" "All users"
    "Disconnected from jabber server." "Disconnected from jabber server."
    "Connected to %s, sending credentials." "Connected to %s, sending credentials."

    "Load History From Logs" "Load History From Logs"
    "Please select how far back you want to load:" \
        "Please select how far back you want to load:"

    "Subject" "Subject"
    "%s - tkchat message" "%s - tkchat message"
    "Re: %s" "Re: %s"
}