#!/bin/sh

echo "Building TkChat installer..."

if [ -d tkchat_build ]
	then
	rm -rf tkchat_build
fi

if [ -f TkChat_Setup.run ]
	then 
	rm TkChat_Setup.run
fi

mkdir tkchat_build
cp tkchat_install_linux tkchat_build/tkchat_install_linux
cp -rf tkchat tkchat_build

makeself ./tkchat_build ./TkChat_Setup.run "Linux Installer for TkChat" ./tkchat_install_linux

echo "Done."

